# Generated by Django 2.0.5 on 2018-05-11 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(default='', max_length=50, unique=True)),
                ('post', models.CharField(choices=[('Teacher', 'Teacher'), ('Student', 'Student')], default='Student', max_length=2)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='ClientMeasure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measures', to='calcs.Client')),
            ],
            options={
                'ordering': ('measure__date',),
            },
        ),
        migrations.CreateModel(
            name='Measure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bottom_border', models.FloatField(default=0)),
                ('upper_border', models.FloatField(default=1)),
                ('r', models.FloatField(default=3.4)),
                ('epsilon', models.FloatField(default=0.001)),
                ('iterations_number', models.IntegerField(default=0)),
                ('function_minimum', models.FloatField(default=0)),
                ('arg_minimum', models.FloatField(default=0)),
                ('date', models.DateTimeField()),
                ('name', models.CharField(max_length=200, unique=True)),
                ('used', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('date',),
            },
        ),
        migrations.AddField(
            model_name='clientmeasure',
            name='measure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calcs.Measure'),
        ),
    ]
