# Generated by Django 2.0.5 on 2018-05-14 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calcs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientmeasure',
            name='client',
        ),
        migrations.RemoveField(
            model_name='clientmeasure',
            name='measure',
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='ClientMeasure',
        ),
    ]
