# Generated by Django 2.0.5 on 2018-05-14 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calcs', '0003_auto_20180514_1858'),
    ]

    operations = [
        migrations.RenameField(
            model_name='measure',
            old_name='used',
            new_name='result_exist',
        ),
        migrations.AddField(
            model_name='measure',
            name='exist_reason',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='measure',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
