# Generated by Django 2.0.5 on 2018-05-16 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calcs', '0004_auto_20180514_2031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measure',
            name='owner',
        ),
    ]
