# Generated by Django 2.0.5 on 2018-05-17 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calcs', '0006_auto_20180517_1807'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measure',
            name='method',
        ),
    ]
