# Generated by Django 2.0.5 on 2018-05-18 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calcs', '0008_measure_graph_image_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='measure',
            name='function',
            field=models.CharField(default='1 + x*x - cos(18*x*x)', max_length=200),
        ),
    ]
