# Generated by Django 2.0.5 on 2018-05-19 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calcs', '0009_measure_function'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measure',
            name='graph_image_filename',
        ),
        migrations.AddField(
            model_name='measure',
            name='graph_image',
            field=models.ImageField(blank=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='measure',
            name='method',
            field=models.CharField(choices=[('gs', 'global_search'), ('pi', 'piyavsky')], default='gs', max_length=2),
        ),
    ]
