# Generated by Django 2.0.5 on 2018-05-19 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calcs', '0010_auto_20180519_1543'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measure',
            name='graph_image',
        ),
        migrations.AddField(
            model_name='measure',
            name='graph_image_filename',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='measure',
            name='method',
            field=models.CharField(choices=[('gs', 'global_search'), ('pi', 'piyavsky')], max_length=2),
        ),
    ]
