# Generated by Django 2.0.5 on 2018-05-19 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calcs', '0011_auto_20180519_1558'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measure',
            name='method',
        ),
    ]
