# Generated by Django 2.0.5 on 2018-05-20 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calcs', '0013_measure_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measure',
            name='method',
            field=models.CharField(choices=[('global_search', 'global_search'), ('piyavsky', 'piyavsky')], default='global_search', max_length=20),
        ),
    ]
