# Generated by Django 2.0.5 on 2018-05-23 18:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('calcs', '0014_auto_20180520_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='measure',
            name='owner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='measure', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
