# Generated by Django 2.0.5 on 2018-05-23 18:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calcs', '0015_measure_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measure',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='measure', to=settings.AUTH_USER_MODEL),
        ),
    ]
