# Generated by Django 2.0.5 on 2018-05-24 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calcs', '0016_auto_20180523_2106'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='measure',
            options={'ordering': ('-date',)},
        ),
    ]
